export const All_SEARCH_REQUEST = 'All_SEARCH_REQUEST'
export const All_SEARCH_SUCCESS = 'All_SEARCH_SUCCESS'
export const All_SEARCH_FAIL = 'All_SEARCH_FAIL'

export const IMAGE_SEARCH_REQUEST = 'IMAGE_SEARCH_REQUEST'
export const IMAGE_SEARCH_SUCCESS = 'IMAGE_SEARCH_SUCCESS'
export const IMAGE_SEARCH_FAIL = 'IMAGE_SEARCH_FAIL'

export const VIDEO_SEARCH_REQUEST = 'VIDEO_SEARCH_REQUEST'
export const VIDEO_SEARCH_SUCCESS = 'VIDEO_SEARCH_SUCCESS'
export const VIDEO_SEARCH_FAIL = 'VIDEO_SEARCH_FAIL'